### ISSUE TITLE
Submitting File by hash always returns 403 forbidden

### ISSUE THREAD

**Issue by BIitzkrieg** [intezer/analyze-scripts#1]
Example code, copied from the analyze_by_hash example, but adjusted to pass it a static hash value, instead of taking an argument. Tried passing hash_value as a regular string and by base64 encoding it.

```
import pprint
import sys
import time
import requests
import base64

base_url = 'https://analyze.intezer.com/api/v2-0'
api_key = 'xxx'
hash_value = 'eb574b236133e60c989c6f472f07827b'

def main():
    response = requests.post(base_url + '/get-access-token', json={'api_key': api_key})
    response.raise_for_status()
    session = requests.session()
    session.headers['Authorization'] = session.headers['Authorization'] = 'Bearer %s' % response.json()['result']

    # trying base64 encoded string... it is a web API after all
    md5base64 = base64.b64encode(hash_value.decode('hex'))
    print(md5base64)
    data = {'hash': md5base64}
    response = session.post(base_url + '/analyze-by-hash', json=data)
    print(response)
    if response.status_code == 404:
        print('File not found')
        return

    assert response.status_code == 201

    while response.status_code != 200:
        time.sleep(1)
        result_url = response.json()['result_url']
        response = session.get(base_url + result_url)
        response.raise_for_status()

    report = response.json()
    pprint.pprint(report)


if __name__ == '__main__':
    main()
```

Result:
```
61dLI2Ez5gyYnG9HLweCew==
<Response [403]>
Traceback (most recent call last):
  File "./intezer.py", line 43, in <module>
    main()
  File "./intezer.py", line 30, in main
    assert response.status_code == 201
AssertionError
```
I tested this with the base code in the repo, passing the hash as an argument and got the same result. However, running the analyze_by_file.py code, and uploading the file for the hash that I used above, works just fine.

**Comment by yoniabrahamy** [comment]
Hi, 
The reason you are receiving 403 Forbidden is because you are probably attempting to use this API with a community edition API key. Currently, analyze-by-hash is not available for community users (unlike analyze-by-file which is available for all users). We will add a comment mentioning that in this example. Also, there is no need to base64 encode the hash before sending it. 

Thank you for bringing this to our attention.

**Comment by BIitzkrieg** [comment]
> Hi,
> The reason you are receiving 403 Forbidden is because you are probably attempting to use this API with a community edition API key. Currently, analyze-by-hash is not available for community users (unlike analyze-by-file which is available for all users). We will add a comment mentioning that in this example. Also, there is no need to base64 encode the hash before sending it.
> 
> Thank you for bringing this to our attention.

Ok, good to know, thanks for the response.
